server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5433/fraud
    username: poleszak
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
service:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
